### ISSUE TITLE
unknown variant `downloadButtonRenderer`

### ISSUE THREAD

**Issue by simon2323** [ATiltedTree/ytextract#68]
### What were you trying to fetch?

Video

### What id does the item have that failed to fetch?

Not bound to a specific video id

### What unexpected error or behavior occurred?

Unable to parse JSON: unknown variant `downloadButtonRenderer`, expected `toggleButtonRenderer` or `buttonRenderer`

### If possible, add the snippet of code that failed.

```rust
let video = client.video(url.parse()?).await?;
```

**Comment by ATiltedTree** [comment]
Should be fixed with v0.10.2.
