### ISSUE TITLE
unknown variant compactPromotedVideoRenderer

### ISSUE THREAD

**Issue by saood06** [ATiltedTree/ytextract#72]
### What were you trying to fetch?

Video

### What id does the item have that failed to fetch?

??? (It did not error on the same video the second time so I don't know)

### What unexpected error or behavior occurred?

Unable to parse JSON: unknown variant `compactPromotedVideoRenderer`, expected one of `compactVideoRenderer`, `compactPlaylistRenderer`, `compactRadioRenderer`, `compactMovieRenderer`, `continuationItemRenderer`, `promotedSparklesWebRenderer` at line 1585 column 44

thread 'main' panicked at 'Encountered fatal error: unknown variant `compactPromotedVideoRenderer`, expected one of `compactVideoRenderer`, `compactPlaylistRenderer`, `compactRadioRenderer`, `compactMovieRenderer`, `continuationItemRenderer`, `promotedSparklesWebRenderer` at line 1585 column 44. Please report this.', C:\...\registry\src\github.com-1ecc6299db9ec823\ytextract-0.10.3\src\youtube\innertube.rs:112:17

I am processing a large (10-30k) number of videos and this seems to be happening randomly, it does not happen on the same video two times in a row, but this will happen and seems to be happening  once per ~250 videos.

### If possible, add the snippet of code that failed.

```rust
yt_client.video(--ID--).await;
```

**Comment by ATiltedTree** [comment]
Should be fixed with v0.10.4!
