### ISSUE TITLE
Video publication date/time

### ISSUE THREAD

**Issue by paulvt** [ATiltedTree/ytextract#88]
### What area does this feature request cover?

Video

### Please describe your request.

It would be nice if besides the views also the publication date (or date/time) would be available for the video.

I wanted to submit a PR, but have been pouring over the JSON dumps and docs to find where but couldn't figure it out.
I assume it is in the player JSON? When pointed the right way, I probably could help out.

**Comment by paulvt** [comment]
I see that `ytextract::video::Video` has a `date` method. It is not a full timestamp but it will do.
I overlooked it because `ytextract::playlist::Video` did not have it. Maybe the `upgrade` method should be highlighted more in the module/struct documentation?

YMMV whether this issue can be closed.

**Comment by ATiltedTree** [comment]
Unfortunately, the JSON data for playlists does not include the publication times of videos. And as such a `upgrade` is required which does another network request to get the data for a specific video. 
But I have added a note to the documentation highlighting the `upgrade` method!
