### ISSUE TITLE
Error: failed to parse JSON on Get Video

### ISSUE THREAD

**Issue by sanihaq** [ATiltedTree/ytextract#95]
### What were you trying to fetch?

Video

### What id does the item have that failed to fetch?

nI2e-J6fsuk

### What unexpected error or behavior occurred?

failed to parse JSON: Error("unknown variant `segmentedLikeDislikeButtonRenderer`, expected one of `toggleButtonRenderer`, `downloadButtonRenderer`, `buttonRenderer`", line: 242, column: 60)', /home/sani/.cargo/registry/src/github.com-1ecc6299db9ec823/ytextract-0.11.1/src/youtube/innertube.rs:133:68

### If possible, add the snippet of code that failed.

```rust
let client = ytextract::Client::new();

 // Request the video
 let video = client.video("nI2e-J6fsuk".parse().unwrap()).await.unwrap();
 // Print it
 println!("{:#?}", video);
```

**Comment by ATiltedTree** [comment]
Should be fixed with v0.11.2
